INSERT INTO job_applied (
        job_id,
        applictaion_sent_date,
        resume_file_name,
        custom_resume,
        cover_letter_sent,
        cover_letter_filename,
        Status
    )
VALUES (
        1,
        '2024-08-12',
        'resume_1.Pdf',
        True,
        True,
        'Cover_letter_01.pdf',
        'Submitted'
    ),
    (
        2,
        '2024-08-15',
        'resume_2.Pdf',
        True,
        True,
        'Cover_letter_02.pdf',
        'Submitted'
    ),
    (
        3,
        '2024-08-28',
        'resume_3.Pdf',
        True,
        false,
        NULL,
        'Submitted'
    ),
    (
        4,
        '2024-09-08',
        NULL,
        False,
        True,
        'Cover_letter_04.pdf',
        'Submitted'
    ),
    (
        5,
        '2024-09-15',
        'resume_1.Pdf',
        True,
        True,
        'Cover_letter_05.pdf',
        'Submitted'
    ),
    (
        6,
        '2024-10-02',
        NULL,
        False,
        False,
        NULL,
        'Submitted'
    );
SELECT *
FROM job_applied;